defmodule EzagentWeb.Endpoint do
  @moduledoc """
  The Phoenix endpoint for `:ezagent_web` — the HTTP/WebSocket entry point that
  runs the plug pipeline and dispatches to `EzagentWeb.Router`.
  """
  use Phoenix.Endpoint, otp_app: :ezagent_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Session cookie domain is env-conditional (task #87): production shares the
  # cookie across *.ezagent.chat subdomains (default below), but on localhost a
  # `.ezagent.chat`-scoped cookie is never stored/sent — which silently breaks
  # all local dev (no session → CSRF 403). dev/test set this to `nil` so the
  # cookie binds to the request host and localhost works like a normal Phoenix
  # app. Default preserves the prod behavior in any env that doesn't override.
  @session_cookie_domain Application.compile_env(
                           :ezagent_web,
                           :session_cookie_domain,
                           ".ezagent.chat"
                         )
  @session_options [
                     store: :cookie,
                     key: "_ezagent_web_key",
                     signing_salt: "TCQlAZge",
                     same_site: "Lax"
                   ] ++ if(@session_cookie_domain, do: [domain: @session_cookie_domain], else: [])

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # AgentBridge canonical bridge socket. The legacy `/cc_socket` alias was
  # removed in Cleanup-3 (FF-4 3→0) after the deprecation window closed; cc
  # Python sidecars now connect to `/agent_bridge` (the MCP config writer
  # default).
  socket "/agent_bridge", Ezagent.AgentBridge.Socket,
    websocket: [check_origin: false],
    longpoll: false

  # Phase 7 completion PR-5: orchestrator MCP transport bridge WS.
  # The orchestrator MCP stdio bridge (ezagent_domain_session's
  # priv/orchestrator_bridge.py) forwards `tools/call` for the 7
  # orchestration tools onto `Ezagent.Orchestrator.McpChannel`. Token
  # auth (reusing the cc TokenStore) at connect; the orchestrator's
  # caller/cap/session context is server-derived from the
  # token-authenticated agent URI.
  socket "/orchestrator_socket", Ezagent.Orchestrator.McpSocket,
    websocket: [check_origin: false],
    longpoll: false

  socket "/socialware_external_socket", EzagentWeb.Socialware.ExternalFeedSocket,
    websocket: [check_origin: false],
    longpoll: false

  # P4 — the CHAT external SPA socket (chat analogue of the external surface socket;
  # caller-identity token → live chat-membership-gated chat_feed projection).
  socket "/socialware_chat_socket", EzagentWeb.Socialware.ChatFeedSocket,
    websocket: [check_origin: false],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ezagent_web,
    gzip: not code_reloading?,
    only: EzagentWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ezagent_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Behind cloudflared the socket peer is the tunnel's private IP for EVERY
  # request; recover the real client IP from `CF-Connecting-IP` (trusted only
  # when the peer is private/loopback) so per-IP rate limits don't collapse
  # into one global bucket. MUST run before RequestId/Telemetry/Router so all
  # logging + `EzagentWeb.RateLimiter` keys see the corrected `remote_ip`.
  plug EzagentWeb.Plugs.CloudflareRemoteIp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # `:length` bounds the request body at the PARSER layer (before any pipeline /
  # controller runs) — the real guard against a huge-body DoS (codex PR-2b #8).
  # 12 MB covers one 10 MB world upload (LV `max_file_size` parity) + multipart
  # overhead; `WorldUploadsController` then enforces the precise ≤10 MB/file and
  # `build_message/3` the ≤5 files/message.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 12_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EzagentWeb.Router
end
