defmodule EzagentWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ezagent_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ezagent_web_key",
    signing_salt: "TCQlAZge",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # AgentBridge PR-C: canonical bridge socket plus legacy cc alias.
  # `/cc_socket` remains for the two-release deprecation window so
  # already-running cc Python sidecars keep their persistent WS path.
  socket "/agent_bridge", Ezagent.AgentBridge.Socket,
    websocket: [check_origin: false],
    longpoll: false

  socket "/cc_socket", Ezagent.AgentBridge.Socket,
    websocket: [check_origin: false],
    longpoll: false

  # Phase 7 completion PR-5: orchestrator MCP transport bridge WS.
  # The orchestrator MCP stdio bridge (ezagent_domain_chat's
  # priv/orchestrator_bridge.py) forwards `tools/call` for the 7
  # orchestration tools onto `Ezagent.Orchestrator.McpChannel`. Token
  # auth (reusing the cc TokenStore) at connect; the orchestrator's
  # caller/cap/session context is server-derived from the
  # token-authenticated agent URI.
  socket "/orchestrator_socket", Ezagent.Orchestrator.McpSocket,
    websocket: [check_origin: false],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ezagent_web,
    gzip: not code_reloading?,
    only: EzagentWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ezagent_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EzagentWeb.Router
end
