%{
  oversized_modules_gt_1500: 5,
  oversized_modules_gt_1000: 17,
  def_count_admin_live: 186,
  def_count_cc_agent: 103,
  def_count_orchestrator_tools: 83,
  def_count_session_creator: 78,
  def_count_capability: 65,
  spawn_registry_call_sites: 38,
  spawn_registry_modules: 32,
  spawn_registry_off_chokepoint_modules: 25,
  create_session_call_sites: 6,
  create_session_modules: 5,
  duplicated_resolve_template_class: 3,
  cc_codex_template_class_combined_loc: 3231,
  raw_home_path_outside_core: 12,
  path_expand_home: 2,
  spawn_fresh_audit_references: 5,
  spawn_fresh_unsanctioned: 0,
  all_slices_occurrences: 3,
  all_slices_unsanctioned: 0,
  set_effect_sites: 118,
  cross_slice_set_violations: 0,
  missing_cap_check_mutating_actions: 0,
  kind_runtime_ordering_violations: 0,
  kind_runtime_reentry_violations: 0,
  cold_restart_respawn_round_trip_drift: 0
}
