defmodule Ezagent.Message do
  @moduledoc """
  Message — Entity ↔ Entity 通信的 envelope。

  Per ARCHITECTURE §3.5 + Decision #39 + #40:Message 是 `%Ezagent.Invocation{}` 的
  特化 args shape,**identity invariant 不可变** —  sender / mentions / body /
  ref_id / inserted_at 跨任意层 routing/forwarding 不变;中转者只创建携带 Message
  的新 Invocation,从不修改 Message 本身。

  ## SPEC v2 §5.13 shape (PR #149)

      id:          "<16 hex>"           # plain UUID (NO `message://` prefix);
                                        # auto-generated by new/3
      sender:      %URI{}               # 谁创建(`entity://user/...` /
                                        # `entity://agent/...`)
      mentions:    [%URI{}]             # @-targets
      body:        %{text: String.t(), attachments: [%URI{}]}  # 结构化
      ref_id:      String.t() | nil     # ^reply-to 另一条 message id
      inserted_at: DateTime.t()
      visibility: :external_visible | :internal
      hops:        non_neg_integer()

  Message is session-internal data, not a dispatchable Kind. The previous
  `message://<uuid>` URI shape was retired in PR #149 / SPEC v2 §5.13 — the
  `id` is now a plain UUID string that lives only inside the messages
  table and the LV stream's `dom_id`.

  ## API

      Ezagent.Message.new(sender, body, opts \\\\ [])

  必填 positional:`sender`(URI)+ `body`(map);其余 opts:
  - `:mentions` — `[URI.t()]`,默认 `[]`
  - `:legend_triggers` — `[String.t()]`,默认 `[]`(VIRTUAL,non-persisted;
    见 schema 注释 — 携带触发的 legend 名,绕过 `:mentions` 的 URI cast)
  - `:ref_id` — `String.t()` 或 `nil`,默认 `nil` (the id of the message
    being replied to)
  - `:inserted_at` — `DateTime.t()`,默认 `DateTime.utc_now()`
  - `:id` — 重写 id(测试 / replay 用,正常不传)
  - `:visibility` — `:external_visible | :internal`, default `:external_visible`
  - `:hops` — non-negative routing hop budget, default `8`

  ## Phase 2 边界

  - `body.attachments` 字段保留(per §10.5 G 设计预留)但 Phase 2 永远 `[]`;
    Phase 5 attachments 接入再用
  - `Jason.Encoder` impl 把 `%URI{}` stringify(否则默认 encoder 把 URI struct
    当 generic struct 序列化所有字段,wire 上膨胀)
  """

  use Ecto.Schema

  # Drop Ecto.Schema's `:__meta__` field from JSON serialization (it's
  # internal Ecto state, not part of the Message envelope on the wire).
  # `:legend_triggers` is a VIRTUAL, ephemeral routing hint (team-routing
  # §3.6, PR-6) — it MUST NOT travel on the wire (PubSub / SSE payloads carry
  # the persisted message shape). Excluded alongside Ecto's internal `:__meta__`.
  @derive {Jason.Encoder, except: [:__meta__, :legend_triggers]}

  @type body_shape :: %{
          required(:text) => String.t(),
          required(:attachments) => [URI.t()]
        }

  @type t :: %__MODULE__{
          id: String.t(),
          session_uri: URI.t() | nil,
          workspace_uri: String.t() | nil,
          sender: URI.t(),
          mentions: [URI.t()],
          legend_triggers: [String.t()],
          body: body_shape(),
          ref_id: String.t() | nil,
          inserted_at: DateTime.t(),
          visibility: :external_visible | :internal,
          hops: non_neg_integer()
        }

  # `id` is the primary key (plain UUID hex); ecto_sqlite3 stores it as TEXT.
  # Disable Ecto's default :id primary key (which would auto-generate integer
  # ids — we want our UUID string to be the PK).
  @primary_key false

  schema "messages" do
    field :id, :string, primary_key: true
    # session_uri is routing metadata (not part of identity invariant per
    # §3.5); caller supplies at MessageStore.write/2 boundary.
    field :session_uri, Ezagent.Ecto.URI
    # Phase 9 PR-6 (SPEC v3 §7) — per-tenant data isolation. NOT NULL at
    # the DB layer; populated by `MessageStore.write/2` via
    # `Ezagent.Persistence.workspace_uri_for!/1` on the session's URI.
    # Stored as canonical `workspace://<name>` string.
    field :workspace_uri, :string
    field :sender, Ezagent.Ecto.URI
    # mentions stored as JSON array of strings (each URI dumped via
    # Ezagent.Ecto.URI.dump → string). ecto_sqlite3 JSON-encodes arrays
    # transparently.
    field :mentions, {:array, Ezagent.Ecto.URI}, default: []
    # team-routing-unification §3.6 (PR-6) — VIRTUAL (NOT persisted): the
    # session-scoped legend NAMEs an inbound message triggered (e.g. CJK
    # `["传话游戏"]`). A legend is a symbolic team handle, NOT a member/agent
    # URI, so its name CANNOT ride `:mentions` (typed `[URI.t()]` via
    # `Ezagent.Ecto.URI` → `URI.new!/1` rejects a CJK / non-URI name and
    # crashes `MessageStore.write`). It rides this virtual field instead, so
    # the rule-set entry's `mention(<legend_name>)` matcher fires through the
    # NORMAL `Resolver.resolve_with_ctx/4` expansion (carrying the entry's
    # `prompt_template_ref`, expanding magic receivers like `$session_members`)
    # WITHOUT touching the persisted message. Because it is virtual, it resets
    # to its default on the re-fetched persisted row — readers in `handle_send`
    # MUST read it off the ORIGINAL inbound `msg`, before the
    # `MessageStore.write/2` round-trip. Default `[]` (behaviour-preserving;
    # a message with no legend trigger behaves exactly as before).
    field :legend_triggers, {:array, :string}, virtual: true, default: []
    # body is a JSON-encoded map per ecto_sqlite3's :map column handling.
    field :body, :map
    # ref_id is a plain string referencing another message id (no URI type,
    # per SPEC v2 §5.13 — message ids are not URIs).
    field :ref_id, :string
    field :inserted_at, :utc_datetime_usec

    field :visibility, Ecto.Enum,
      values: [:external_visible, :internal],
      default: :external_visible

    field :hops, :integer, default: 8

    # The ROUTE-INTO-THIS-SESSION timestamp — set fresh at `MessageStore.write/2`
    # (= when the message entered THIS session). After the message
    # session-scoping collapse (2026-06-21, multi-routing removed) this is a REAL
    # column on `messages` (was virtual, surfaced from the dropped
    # `message_routings.routed_at`). The chat-feed snapshot orders on it so a
    # cross-session-FORWARDED message (a NEW copy in the target session, per the
    # copy+ref model) windows at its arrival time here, not the original's
    # creation time. `inserted_at` remains the message CREATION time for
    # pagination + the customer feed.
    field :routed_at, :utc_datetime_usec
  end

  @doc """
  Construct a new Message.

  Auto-generates `id` via 8 random bytes (16 hex chars), a plain UUID
  string with no `message://` prefix. Caller can override via `:id` opt
  for tests / message replay scenarios.
  """
  @spec new(URI.t(), body_shape(), keyword()) :: t()
  def new(%URI{} = sender, %{text: text} = body, opts \\ []) when is_binary(text) do
    %__MODULE__{
      id: Keyword.get(opts, :id, generate_id()),
      sender: sender,
      mentions: Keyword.get(opts, :mentions, []),
      legend_triggers: Keyword.get(opts, :legend_triggers, []),
      body: Map.put_new(body, :attachments, []),
      ref_id: Keyword.get(opts, :ref_id),
      inserted_at: Keyword.get(opts, :inserted_at, DateTime.utc_now()),
      visibility: Keyword.get(opts, :visibility, :external_visible),
      hops: Keyword.get(opts, :hops, 8)
    }
  end

  defp generate_id do
    Base.encode16(:crypto.strong_rand_bytes(8), case: :lower)
  end
end

# Jason encoder for `%URI{}` — stringify on the wire instead of dumping struct
# fields. Required so Message + body + mentions serialize cleanly to JSON
# (e.g., LV PubSub payloads, SSE bridge events). Defined here in ezagent_core
# (the package that introduces URI as a first-class data type for messages).
defimpl Jason.Encoder, for: URI do
  def encode(uri, opts) do
    Jason.Encode.string(URI.to_string(uri), opts)
  end
end

# Note: `%Ezagent.Message{}` JSON encoding is via `@derive {Jason.Encoder,
# except: [:__meta__]}` at the schema declaration (see top of module).
# That handles `:__meta__` (Ecto's internal field) cleanly. No manual
# defimpl needed.
