defmodule Ezagent.ProducerEnumerator do
  @moduledoc """
  V5 pid-closure (use side), B1/D2 — the Kind-mailbox PRODUCER enumerator
  (REPORT-ONLY).

  Its OWN module — deliberately NOT an extension of
  `Ezagent.ActorBoundaryScanner` (that integration is coordinated later
  with the obtain-side track; the shared-file constraint for B1).

  ## What it enumerates

  Every site in `apps/*/lib/**` (the actor app INCLUDED) that can put a
  message into a Kind mailbox WITHOUT the framework signal envelope
  (`%EzagentActor.Signal{}`, built additive in B1/D1):

    * raw sends — bare `send/2` (== `Kernel.send/2`; skipped when the file
      defines a local `send/2`, same disambiguation idiom as the
      boundary scanner's bare-`spawn` guard), qualified `Kernel.send/2`,
      `:erlang.send/2,3`, `Process.send/2,3`;
    * raw timers — `Process.send_after/3,4` / `:erlang.send_after/3,4`;
    * PubSub fan-out — `Phoenix.PubSub.broadcast/3` / `local_broadcast/3`
      (a Kind subscribed to the topic receives the raw term);
    * `Ezagent.Runtime.Resolver.send_envelope/2` — the seam's raw-send
      escape hatch (on the dead-code ledger for the final cleanup; D1's
      `EzagentActor.Signal.signal/2` is its one sanctioned user).

  Run EMPTY-ALLOWLIST — there are no exempt files. The handful of hits
  inside `apps/ezagent_actor/lib/ezagent_actor/signal.ex` /
  `signal/monitor.ex` are the B1 transport's OWN envelope sends,
  enumerated (not exempted) and labelled in the generated worklist.

  ## Site shape column

  Each site carries the STATICALLY-VISIBLE message literal: an atom
  (`:ezagent_ce_reconcile`), a `{head, size}` tuple summary
  (`{:ezagent_run_deferred, 2}`), or `:dynamic` (runtime-computed —
  inspect manually at migration time). Module attributes bound to literal
  atoms / atom-headed tuples (`@ce_reconcile_signal
  :ezagent_ce_reconcile`) are resolved.

  ## The honest guarantee (anti-drift)

  Same posture as the track-A acquisition census: this proves "no
  ENUMERATED producer primitive occurs outside this list". It does NOT
  prove no other path can reach a Kind mailbox (a pid can flow out of an
  allowlisted call through a tuple/struct) — that needs taint tracking,
  out of scope BY DESIGN. Report-only: nothing here gates CI.

  The generated worklist is `docs/notes/v5-use-side-producer-worklist.md`,
  regenerated by
  `apps/ezagent_core/test/invariants/producer_enumerator_worklist_test.exs`.
  """

  # The producer-primitive ban table: `{module, fun, arities, msg_arg_index}`.
  # `msg_arg_index` is the 0-based position of the MESSAGE argument (for the
  # static shape column). Resolved through the per-file alias table, so
  # aliased and fully-qualified call sites both match.
  @primitives [
    {Process, :send, [2, 3], 1},
    {Process, :send_after, [3, 4], 1},
    {:erlang, :send, [2, 3], 1},
    {:erlang, :send_after, [3, 4], 1},
    {Phoenix.PubSub, :broadcast, [3], 2},
    {Phoenix.PubSub, :local_broadcast, [3], 2},
    {Ezagent.Runtime.Resolver, :send_envelope, [2], 1},
    {Kernel, :send, [2], 1}
  ]

  @doc """
  The repository root (absolute). Resolved from the working directory (the
  mix test / task cwd), NOT a compile-time `__DIR__` — a dev/CI
  source-tree scanner, same idiom as `Ezagent.ActorBoundaryScanner`.
  """
  def repo_root do
    cwd = File.cwd!()
    if File.dir?(Path.join(cwd, "apps")), do: cwd, else: Path.expand("../..", cwd)
  end

  @doc """
  All producer sites in the tree (REPORT-ONLY census, empty allowlist).

  Each entry: `%{path, target, line, shape, sha}` — `target` is e.g.
  `"Kernel.send/2"`, `shape` the statically-visible message summary
  (atom / `{head, size}` / `:dynamic`), `sha` content-anchors the source
  line (same ratchet idiom as the boundary gate, ready for a later
  enforcement phase). Deterministically sorted.
  """
  @spec sites() :: [map()]
  def sites do
    root = repo_root()

    root
    |> Path.join("apps/*/lib/**/*.ex")
    |> Path.wildcard()
    |> Enum.flat_map(fn abs ->
      rel = Path.relative_to(abs, root)
      sites_in_source(File.read!(abs), rel)
    end)
    |> Enum.sort_by(&{&1.path, &1.line, &1.target})
    |> Enum.uniq()
  end

  @doc false
  def sites_in_source(source, rel) do
    case Code.string_to_quoted(source) do
      {:ok, ast} ->
        ctx = %{
          aliases: collect_aliases(ast),
          local_funs: local_fun_names(ast),
          attrs: literal_attributes(ast)
        }

        lines = String.split(source, "\n")

        {_, hits} =
          Macro.prewalk(ast, [], fn node, acc ->
            {node, producer_hit(node, ctx) ++ acc}
          end)

        hits
        |> Enum.map(fn %{target: t, line: l, shape: s} ->
          %{path: rel, target: t, line: l, shape: s, sha: line_sha(lines, l)}
        end)
        |> Enum.uniq()

      {:error, _} ->
        []
    end
  end

  # ── Site detection ─────────────────────────────────────────────────────────

  # Qualified call `Mod.fun(args…)` against the primitive table.
  defp producer_hit({{:., _, [modast, fun]}, meta, args}, ctx)
       when is_atom(fun) and is_list(args) do
    module = resolve_ast(modast, ctx.aliases)
    arity = length(args)

    case primitive(module, fun, arity) do
      nil -> []
      msg_index -> [hit(target_name(module, fun, arity), shape_at(args, msg_index, ctx), meta)]
    end
  end

  # Bare `send(pid, msg)` — flagged only when the file defines NO local
  # function named `send` (otherwise it is a local call, not `Kernel.send/2`).
  defp producer_hit({:send, meta, args}, ctx) when is_list(args) and length(args) == 2 do
    if MapSet.member?(ctx.local_funs, :send),
      do: [],
      else: [hit("Kernel.send/2", shape_at(args, 1, ctx), meta)]
  end

  defp producer_hit(_node, _ctx), do: []

  defp primitive(module, fun, arity) do
    Enum.find_value(@primitives, fn {mod, f, arities, msg_index} ->
      if module == mod and fun == f and arity in arities, do: msg_index, else: nil
    end)
  end

  defp target_name(module, fun, arity) when is_atom(module) do
    name =
      case Atom.to_string(module) do
        "Elixir." <> rest -> rest
        erl -> ":" <> erl
      end

    "#{name}.#{fun}/#{arity}"
  end

  # ── Static message-shape summary ───────────────────────────────────────────
  #
  # The statically-visible message literal: an atom, a `{head, size}` tuple
  # summary, or `:dynamic`. Module attributes bound to literals are resolved
  # one hop (no recursion into aliases/interpolation — those stay :dynamic).

  defp shape_at(args, index, ctx) do
    args |> Enum.at(index) |> shape_of(ctx)
  end

  defp shape_of(atom, _ctx) when is_atom(atom), do: atom

  # Literal 2-tuple (no `:{}` wrapper in AST) with an atom head.
  defp shape_of({head, _second}, _ctx) when is_atom(head), do: {head, 2}

  # Literal N-tuple (`:{}/3` AST) with an atom head.
  defp shape_of({:{}, _, [head | _] = elems}, _ctx) when is_atom(head),
    do: {head, length(elems)}

  # Module attribute bound to a literal (e.g. `@signal :ezagent_ce_reconcile`).
  defp shape_of({:@, _, [{name, _, actx}]}, ctx)
       when is_atom(name) and (is_atom(actx) or is_nil(actx)) do
    case Map.fetch(ctx.attrs, name) do
      {:ok, literal} -> shape_of(literal, ctx)
      :error -> :dynamic
    end
  end

  defp shape_of(_other, _ctx), do: :dynamic

  # `@name <literal atom | literal atom-headed tuple>` definitions.
  defp literal_attributes(ast) do
    {_, attrs} =
      Macro.prewalk(ast, %{}, fn
        {:@, _, [{name, _, [value]}]} = node, acc when is_atom(name) ->
          if literal_value?(value), do: {node, Map.put(acc, name, value)}, else: {node, acc}

        node, acc ->
          {node, acc}
      end)

    attrs
  end

  defp literal_value?(value) when is_atom(value), do: true
  defp literal_value?({head, _}) when is_atom(head), do: true
  defp literal_value?({:{}, _, [head | _]}) when is_atom(head), do: true
  defp literal_value?(_other), do: false

  # ── AST helpers (same idioms as the boundary scanner, own copies) ──────────

  defp hit(target, shape, meta),
    do: %{target: target, shape: shape, line: Keyword.get(meta, :line, 0)}

  defp line_sha(lines, line) do
    lines
    |> Enum.at(line - 1, "")
    |> String.trim()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  defp resolve_ast({:__aliases__, _, parts}, aliases) when is_list(parts) do
    if Enum.all?(parts, &is_atom/1), do: resolve(parts, aliases), else: nil
  end

  defp resolve_ast(mod, _aliases) when is_atom(mod), do: mod
  defp resolve_ast(_other, _aliases), do: nil

  defp resolve([first | rest], aliases) do
    parts =
      case Map.get(aliases, first) do
        nil -> [first | rest]
        full -> full ++ rest
      end

    if Enum.all?(parts, &is_atom/1), do: Module.concat(parts), else: nil
  end

  defp collect_aliases(ast) do
    {_, acc} =
      Macro.prewalk(ast, %{}, fn
        {:alias, _, [{{:., _, [{:__aliases__, _, prefix}, :{}]}, _, kids}]} = node, acc
        when is_list(kids) ->
          acc =
            Enum.reduce(kids, acc, fn
              {:__aliases__, _, [last]}, a -> Map.put(a, last, prefix ++ [last])
              _, a -> a
            end)

          {node, acc}

        {:alias, _, [{:__aliases__, _, parts}]} = node, acc ->
          {node, Map.put(acc, List.last(parts), parts)}

        {:alias, _, [{:__aliases__, _, parts}, opts]} = node, acc when is_list(opts) ->
          case Keyword.get(opts, :as) do
            {:__aliases__, _, [as_name]} -> {node, Map.put(acc, as_name, parts)}
            _ -> {node, acc}
          end

        node, acc ->
          {node, acc}
      end)

    acc
  end

  # Names of all local def/defp/defmacro functions in this file (for the
  # bare-`send` vs local-call disambiguation).
  defp local_fun_names(ast) do
    {_, names} =
      Macro.prewalk(ast, MapSet.new(), fn
        {kind, _, [head | _]} = node, acc when kind in [:def, :defp, :defmacro] ->
          case fn_name(head) do
            name when is_atom(name) -> {node, MapSet.put(acc, name)}
            _ -> {node, acc}
          end

        node, acc ->
          {node, acc}
      end)

    names
  end

  defp fn_name({:when, _, [inner | _]}), do: fn_name(inner)
  defp fn_name({name, _, _}) when is_atom(name), do: name
  defp fn_name(_), do: nil

  # ── Worklist markdown ──────────────────────────────────────────────────────

  @doc """
  Render the producer census as the committed report-only worklist
  markdown (`docs/notes/v5-use-side-producer-worklist.md`) — the B2
  migration worklist authority (enumerator-first, NOT a hand-list).
  Deterministic.
  """
  @spec worklist_markdown([map()]) :: String.t()
  def worklist_markdown(sites) do
    rows =
      Enum.map_join(sites, "\n", fn s ->
        "| `#{s.target}` | `#{shape_render(s.shape)}` | `#{s.path}:#{s.line}` | #{transport_note(s.path)} | `#{String.slice(s.sha, 0, 12)}` |"
      end)

    primitives =
      @primitives
      |> Enum.flat_map(fn {mod, fun, arities, _} ->
        Enum.map(arities, &target_name(mod, fun, &1))
      end)
      |> Enum.uniq()
      |> Enum.map_join(", ", &"`#{&1}`")

    """
    # V5 pid-closure — Track B (use side): producer worklist (REPORT-ONLY)

    > Generated by `Ezagent.ProducerEnumerator.sites/0` via
    > `mix test apps/ezagent_core/test/invariants/producer_enumerator_worklist_test.exs`.
    > **Report-only**: this is a census, NOT a gate — no entry here fails CI,
    > and the enforcement flip is a separate later phase (B2/B3, human decision).
    > This is the B2 migration worklist authority — enumerator-first, NOT a
    > hand-list.

    Every site in `apps/*/lib/**` (the actor app INCLUDED, empty allowlist)
    that can put a message into a Kind mailbox WITHOUT the framework signal
    envelope (`%EzagentActor.Signal{}`, built additive in B1/D1):

    - raw sends — bare `send/2` (== `Kernel.send/2`; a file defining a local
      `send/2` is not flagged for bare calls), qualified `Kernel.send/2`,
      `:erlang.send/2,3`, `Process.send/2,3`;
    - raw timers — `Process.send_after/3,4`, `:erlang.send_after/3,4`;
    - PubSub fan-out — `Phoenix.PubSub.broadcast/3` / `local_broadcast/3`
      (a Kind subscribed to the topic receives the raw term);
    - `Ezagent.Runtime.Resolver.send_envelope/2` — the seam's raw-send
      escape hatch (on the dead-code ledger for the final cleanup; B1's
      `EzagentActor.Signal.signal/2` is its one sanctioned user).

    Primitives detected: #{primitives}, plus the bare `send/2` form
    (`Kernel.send/2`) where the file defines no local `send/2`.

    Rows marked **transport** are the B1 sanctioned transport's OWN
    envelope sends (`apps/ezagent_actor/lib/ezagent_actor/signal.ex`,
    `signal/monitor.ex`) — enumerated by the empty allowlist, NOT B2
    migration targets.

    The **Shape** column is the statically-visible message literal: an
    atom, a `{head, size}` tuple summary, or `:dynamic` (runtime-computed
    — inspect manually at migration time). Module attributes bound to
    literal atoms / atom-headed tuples are resolved.

    **The honest guarantee** (restated from the enumerator moduledoc):
    this worklist proves "no ENUMERATED producer primitive occurs outside
    this list" (ANTI-DRIFT). It does NOT prove no other path can reach a
    Kind mailbox — that needs taint tracking, out of scope by design.

    **#{length(sites)} entries.**

    | Primitive | Shape | File:Line | Note | Line SHA (12) |
    |---|---|---|---|---|
    #{rows}
    """
  end

  @transport_files [
    "apps/ezagent_actor/lib/ezagent_actor/signal.ex",
    "apps/ezagent_actor/lib/ezagent_actor/signal/monitor.ex"
  ]

  defp transport_note(path) do
    if path in @transport_files, do: "**transport**", else: ""
  end

  defp shape_render(:dynamic), do: ":dynamic"
  defp shape_render(shape) when is_atom(shape), do: inspect(shape)
  defp shape_render({head, size}), do: "{#{inspect(head)}, #{size}}"
end
