import Config

# Show debug info in the branded 500 error page when it renders (in dev,
# Plug.Debugger usually catches first; this controls the fallback case).
config :ezagent_web, :show_error_debug, true

# Configure your database
#
# Path follows the same env-var logic as `Ezagent.Home` (which lives in
# ezagent_core/lib and isn't loadable at config-time, so we inline the
# logic here): `$EZAGENT_HOME / $EZAGENT_PROFILE / db / ezagent_core.db`,
# defaulting to `~/.ezagent / default / db / ezagent_core.db`.
#
# Two evaluation points:
#   compile-time (this file) — pinned at the moment `mix compile` runs;
#     used by plain mix tasks (ezagent.user.set_password etc.) that don't
#     evaluate runtime.exs.
#   runtime — config/runtime.exs re-evaluates the same path so
#     `EZAGENT_HOME=/other mix phx.server` picks up the override.
#
# Phase 6 PR 1 — see `mix ezagent.home.adopt_db` for one-time migration.
esr_home_dev = System.get_env("EZAGENT_HOME", "~/.ezagent") |> Path.expand()
esr_profile_dev = System.get_env("EZAGENT_PROFILE", "default")

config :ezagent_core, EzagentCore.Repo,
  database: Path.join([esr_home_dev, esr_profile_dev, "db", "ezagent_core.db"]),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ezagent_web, EzagentWeb.Endpoint,
  # Bound to 0.0.0.0 so the dev server is reachable over the tailnet — Allen
  # accesses esr-ng from a tailnet IP (100.x.x.x), not localhost (P0-D8).
  # `check_origin: false` below is required for the same reason: a LiveView WS
  # connection from a 100.x origin would otherwise be rejected. dev-only.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "10042")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LB/r5X+0G50lTmGaZonOO8PxwMhtOxdS3J308T7s+w3fBI0R8fkZbABhqZxjOFqO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ezagent_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ezagent_web, ~w(--watch)]}
  ]

# Resource-unification P2 — upload download-token signing secret (core-owned
# config key). Wired to the same value as the web endpoint's secret_key_base so
# the token minted in ezagent_web/ezagent_plugin_liveview verifies identically.
config :ezagent_core, Ezagent.Uploads.DownloadToken,
  secret_key_base: "LB/r5X+0G50lTmGaZonOO8PxwMhtOxdS3J308T7s+w3fBI0R8fkZbABhqZxjOFqO"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ezagent_web, EzagentWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ezagent_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ezagent_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
