defmodule Ezagent.Mail.EzagentChatAdapterTest do
  @moduledoc """
  Unit tests for the `email.ezagent.chat` REST Swoosh adapter. The pure
  `build_request/2` is asserted offline; `deliver/2` is exercised with an
  injected `:http_request_fun` (no network) to prove 2xx→{:ok,_},
  non-2xx→{:error,_}, and transport-error→{:error,_} mapping.
  """
  # async: false — flips the :ezagent_web, :http_request_fun app env.
  use ExUnit.Case, async: false

  alias Ezagent.Mail.EzagentChatAdapter
  import Swoosh.Email

  @config [base_url: "https://email.ezagent.chat", api_key: "emk_test_key"]

  defp built_email do
    new()
    |> to("recipient@example.com")
    |> from({"Ezagent", "auth@ezagent.chat"})
    |> subject("Your Ezagent sign-in link")
    |> text_body("open https://app/auth/magic/abc")
    |> html_body("<p>open <a href=\"https://app/auth/magic/abc\">link</a></p>")
  end

  describe "build_request/2 (pure)" do
    test "targets /api/send with a Bearer header and the right JSON body" do
      {url, headers, content_type, body} =
        EzagentChatAdapter.build_request(built_email(), @config)

      assert url == ~c"https://email.ezagent.chat/api/send"
      assert content_type == ~c"application/json"
      assert {~c"authorization", ~c"Bearer emk_test_key"} in headers

      decoded = Jason.decode!(body)
      assert decoded["address"] == "auth@ezagent.chat"
      assert decoded["to"] == ["recipient@example.com"]
      assert decoded["subject"] == "Your Ezagent sign-in link"
      assert decoded["text"] =~ "auth/magic/abc"
      assert decoded["html"] =~ "auth/magic/abc"
    end

    test "trims a trailing slash on base_url" do
      {url, _, _, _} =
        EzagentChatAdapter.build_request(built_email(), base_url: "https://x/", api_key: "k")

      assert url == ~c"https://x/api/send"
    end

    test "omits html when there is no html body" do
      email =
        new()
        |> to("r@example.com")
        |> from({"Ezagent", "auth@ezagent.chat"})
        |> subject("s")
        |> text_body("t")

      {_, _, _, body} = EzagentChatAdapter.build_request(email, @config)
      refute Map.has_key?(Jason.decode!(body), "html")
    end

    test "always sends `to` as an array, single or many recipients" do
      one = new() |> to("a@x.com") |> from("s@ezagent.chat") |> subject("s") |> text_body("t")
      {_, _, _, b1} = EzagentChatAdapter.build_request(one, @config)
      assert Jason.decode!(b1)["to"] == ["a@x.com"]

      many =
        new()
        |> to("a@x.com")
        |> to("b@x.com")
        |> from("s@ezagent.chat")
        |> subject("s")
        |> text_body("t")

      {_, _, _, b2} = EzagentChatAdapter.build_request(many, @config)
      to = Jason.decode!(b2)["to"]
      assert is_list(to)
      assert Enum.sort(to) == ["a@x.com", "b@x.com"]
    end
  end

  describe "deliver/2 (injected transport)" do
    setup do
      on_exit(fn -> Application.delete_env(:ezagent_web, :http_request_fun) end)
      :ok
    end

    defp stub_http(fun) do
      Application.put_env(:ezagent_web, :http_request_fun, fun)
    end

    test "2xx → {:ok, %{id: ...}} and POSTs the built request" do
      test_pid = self()

      stub_http(fn method, request, _http_opts, _opts ->
        send(test_pid, {:sent, method, request})
        {:ok, {{~c"HTTP/1.1", 202, ~c"Accepted"}, [], ~c"{\"id\":\"msg_123\"}"}}
      end)

      assert {:ok, %{id: "msg_123"}} = EzagentChatAdapter.deliver(built_email(), @config)

      assert_received {:sent, :post, {url, headers, ~c"application/json", body}}
      assert url == ~c"https://email.ezagent.chat/api/send"
      assert {~c"authorization", ~c"Bearer emk_test_key"} in headers
      assert Jason.decode!(body)["to"] == ["recipient@example.com"]
    end

    test "non-2xx → {:error, {:http, status, body}}" do
      stub_http(fn _m, _r, _h, _o ->
        {:ok, {{~c"HTTP/1.1", 403, ~c"Forbidden"}, [], ~c"{\"error\":\"not owner\"}"}}
      end)

      assert {:error, {:http, 403, body}} = EzagentChatAdapter.deliver(built_email(), @config)
      assert body =~ "not owner"
    end

    test "transport error → {:error, reason}, never raises" do
      stub_http(fn _m, _r, _h, _o -> {:error, :timeout} end)
      assert {:error, :timeout} = EzagentChatAdapter.deliver(built_email(), @config)
    end
  end

  describe "validate_config/1 (auto-generated by use Swoosh.Adapter)" do
    test "passes with base_url + api_key" do
      assert EzagentChatAdapter.validate_config(@config) == :ok
    end

    test "raises when a required key is missing" do
      assert_raise ArgumentError, fn ->
        EzagentChatAdapter.validate_config(base_url: "https://x")
      end
    end
  end
end
