defmodule Mix.Tasks.World.Renderers.Manifest do
  @moduledoc """
  Generates the static React renderer registry from installed plugin declarations.

      mix world.renderers.manifest
      mix world.renderers.manifest --check
  """

  use Mix.Task

  @shortdoc "Generate the plugin-page React renderer manifest"
  @requirements ["compile"]

  @impl Mix.Task
  def run(args) do
    generated = build_pages() |> generated_source()
    path = manifest_path()

    if "--check" in args do
      if File.read(path) != {:ok, generated} do
        Mix.raise(
          "world renderer manifest is stale — run `mix world.renderers.manifest` and commit #{Path.relative_to_cwd(path)}"
        )
      end

      Mix.shell().info("world renderer manifest in sync (#{Path.relative_to_cwd(path)})")
    else
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, generated)
      Mix.shell().info("wrote #{Path.relative_to_cwd(path)}")
    end
  end

  @doc false
  def generated_source(pages \\ Ezagent.World.PluginPageRegistry.pages()) do
    # Flatten every page's optional `:unfurl` entries, carrying the owning page
    # so the import path resolves against that plugin's app (same as page renderers).
    unfurls =
      pages
      |> Enum.flat_map(fn page ->
        page |> Map.get(:unfurl, []) |> Enum.map(&{page, &1})
      end)
      |> Enum.with_index()

    imports =
      (Enum.map(Enum.with_index(pages), fn {page, index} ->
         "import {#{page.renderer.export} as Renderer#{index}} from #{Jason.encode!(import_path(page))}"
       end) ++
         Enum.map(unfurls, fn {{page, entry}, index} ->
           "import {#{entry.renderer.export} as Unfurl#{index}} from #{Jason.encode!(import_path(page, entry.renderer.source))}"
         end))
      |> Enum.join("\n")

    entries =
      pages
      |> Enum.with_index()
      |> Enum.map_join(",\n", fn {page, index} ->
        "  #{Jason.encode!(page.key)}: Renderer#{index}"
      end)

    full_bleed =
      pages
      |> Enum.filter(& &1.renderer.full_bleed)
      |> Enum.map(& &1.key)
      |> Jason.encode!()

    unfurl_body =
      case unfurls do
        [] ->
          "[]"

        _ ->
          records =
            Enum.map_join(unfurls, ",\n", fn {{_page, entry}, index} ->
              "  {id: #{Jason.encode!(entry.id)}, pattern: new RegExp(#{Jason.encode!(entry.pattern)}), component: Unfurl#{index}}"
            end)

          "[\n#{records}\n]"
      end

    """
    // Generated by mix world.renderers.manifest. DO NOT EDIT.
    import type {ComponentType} from "react"
    import type {UnfurlRendererEntry} from "../components/unfurl"
    #{imports}

    export type PluginPageRendererProps = {
      component: {id: string; type: string}
      state: Record<string, unknown>
      onAction: (action: string, args: Record<string, unknown>) => void
    }

    export const pluginPageRenderers: Record<string, ComponentType<PluginPageRendererProps>> = {
    #{entries}
    }

    export const pluginPageFullBleedFamilies = new Set<string>(#{full_bleed})

    export const pluginUnfurlRenderers: UnfurlRendererEntry[] = #{unfurl_body}
    """
  end

  @doc false
  def manifest_path do
    Path.expand("../../../assets/src/generated/plugin-page-renderers.tsx", __DIR__)
  end

  defp import_path(page), do: import_path(page, page.renderer.source)

  # Resolve a `assets/src/...` source (a page renderer OR an unfurl renderer)
  # declared by `page`'s provider into a path relative to the generated manifest.
  defp import_path(page, source) do
    app =
      Application.get_application(page.provider) ||
        Enum.find(Map.keys(Mix.Project.apps_paths()), fn app ->
          Application.get_env(app, :ezagent_plugin) == page.provider
        end) ||
        raise "cannot resolve OTP application for UI provider #{inspect(page.provider)}"

    app_path =
      Mix.Project.apps_paths()[app] || Path.join(umbrella_root(), "apps/#{app}")

    unless File.dir?(app_path) do
      raise "cannot resolve umbrella path for plugin application #{inspect(app)}"
    end

    resolved =
      source
      |> Path.rootname()
      |> Path.expand(app_path)

    relative = Path.relative_to(resolved, Path.dirname(manifest_path()), force: true)

    if String.starts_with?(relative, "."), do: relative, else: "./" <> relative
  end

  defp build_pages do
    declarations =
      Mix.Project.apps_paths()
      |> Enum.map(fn {app, _path} ->
        ebin = Path.join([Mix.Project.build_path(), "lib", Atom.to_string(app), "ebin"])
        Code.prepend_path(ebin)
        plugin_provider_from_app_file(app, ebin)
      end)
      |> Enum.reject(&is_nil/1)
      |> Enum.sort_by(&inspect/1)
      |> Enum.filter(fn provider ->
        Code.ensure_loaded?(provider) and function_exported?(provider, :pages, 0)
      end)
      |> Enum.map(fn provider -> {provider, provider.pages()} end)

    case Ezagent.World.PluginPageRegistry.resolve(declarations) do
      %{pages: pages, diagnostics: []} ->
        pages

      %{diagnostics: diagnostics} ->
        Mix.raise("invalid plugin UI declarations: #{inspect(diagnostics)}")
    end
  end

  defp umbrella_root, do: Path.expand("../../../../..", __DIR__)

  defp plugin_provider_from_app_file(app, ebin) do
    app_file = Path.join(ebin, "#{app}.app")

    with {:ok, [{:application, ^app, properties}]} <- :file.consult(String.to_charlist(app_file)),
         env when is_list(env) <- Keyword.get(properties, :env, []),
         provider when is_atom(provider) <- Keyword.get(env, :ezagent_plugin) do
      provider
    else
      _ -> nil
    end
  end
end
