defmodule EzagentPluginHello.Integration.HelloPageE2ETest do
  @moduledoc """
  The hello Phase-0 vertical slice, end to end on the substrate (no live LLM):

      App.ensure_app (public_view session + joined builder member)
        → TurnDriver.drive(session, spec)            # the page chokepoint
        → Behavior.Surface.put_version + approve     # via turn.compose/settle
        → CustomerFeed.snapshot(session, anon token) # what the anon visitor sees

  This proves the same path a real generation takes, with a fixed catalog spec
  standing in for the LLM output (the LLM round-trip is exercised separately; the
  spec it must emit is catalog-validated in `EzagentPluginHello.SpecTest`).
  """
  use EzagentCore.DataCase, async: false

  alias Ezagent.Workspace
  alias Ezagent.Socialware.{CustomerAuth, CustomerFeed}
  alias EzagentPluginHello.{App, Spec, TurnDriver}

  setup do
    ws = "hello-e2e-#{System.unique_integer([:positive])}"
    {:ok, _ws_pid} = Workspace.create(ws, %{})

    {:ok, session_uri, builder_uri} = App.ensure_app(ws, "main")
    token = CustomerAuth.issue_token(session_uri, Ezagent.Capability.workspace_of(session_uri))

    %{session: session_uri, builder: builder_uri, token: token}
  end

  test "an anonymous customer sees the catalog page the builder lands via Surface", ctx do
    spec = %{
      "type" => "page",
      "props" => %{"title" => "Hello E2E"},
      "children" => [
        %{
          "type" => "heading",
          "props" => %{"text" => "Generated by the hello builder", "level" => 1},
          "children" => []
        },
        %{
          "type" => "text",
          "props" => %{"text" => "An anonymous visitor can read this page."},
          "children" => []
        }
      ]
    }

    # The spec is catalog-constrained (the safety property the renderer relies on).
    assert {:ok, ^spec} = Spec.validate(spec)

    # Before any turn: the customer surface has no approved page.
    assert {:ok, before} = CustomerFeed.snapshot(ctx.session, ctx.token)
    assert before.page == nil

    # Drive one turn to land the page (the only way a page is born).
    assert {:ok, _turn_id} = TurnDriver.drive(ctx.session, spec, "Generated your page.")

    snapshot = wait_for_page(ctx.session, ctx.token)

    # The anon visitor sees exactly the approved spec + the customer-visible summary.
    assert snapshot.page == spec
    assert Enum.any?(snapshot.messages, &(text_of(&1) == "Generated your page."))
  end

  test "ensure_app equips the builder with the within-session orchestrator cap", ctx do
    # The orchestrator's granted caps live in its `:identity` slice (the Identity/
    # IdentityAdmin behaviors own `:caps` there). This is the set PR-4's TurnDriver
    # reads + presents when it calls `add_managed_member`.
    {:ok, %{caps: caps}} = Ezagent.Kind.get_slice(ctx.builder, :identity)

    # Cap #1 — the scope-bounded `{:within_session, S}` delegation a real
    # orchestrator holds, the cap `add_managed_member` preflights before spawning.
    assert Enum.any?(caps, fn
             %Ezagent.Capability{kind: :session, instance: {:within_session, %URI{} = s}} ->
               URI.to_string(s) == URI.to_string(ctx.session)

             _ ->
               false
           end)

    # The actual spawn-path gate accepts the builder's caps.
    assert :ok = Ezagent.Orchestrator.Tools.preflight_within_session_cap(caps, ctx.session)
  end

  # --- helpers ---------------------------------------------------------------

  defp wait_for_page(session, token, attempts \\ 150)

  defp wait_for_page(_session, _token, 0),
    do: flunk("customer snapshot never exposed an approved page")

  defp wait_for_page(session, token, attempts) do
    case CustomerFeed.snapshot(session, token) do
      {:ok, %{page: page} = snapshot} when not is_nil(page) ->
        snapshot

      _ ->
        Process.sleep(20)
        wait_for_page(session, token, attempts - 1)
    end
  end

  defp text_of(message) do
    Map.get(message.body, "text") || Map.get(message.body, :text)
  end
end
