defmodule EzagentPluginHello.Integration.HelloPageE2ETest do
  @moduledoc """
  The hello Phase-0 vertical slice, end to end on the substrate (no live LLM):

      App.ensure_app (public_view session + joined orchestrator front desk)
        → TurnDriver.drive(session, spec)            # the page chokepoint
        → Behavior.Surface.put_version + approve     # via turn.compose/settle
        → ExternalFeed.snapshot(session, anon)       # what the anon visitor sees

  This proves the same path a real generation takes, with a fixed catalog spec
  standing in for the LLM output (the LLM round-trip is exercised separately; the
  spec it must emit is catalog-validated in `EzagentPluginHello.SpecTest`).

  The viewer is a real minted read-only **anon-User** joined to the public_view
  session — the production ingress (#51 §4.1, what `ExternalFeedController` does
  for an anonymous visitor) — and the read is authorized by LIVE membership, not
  an identity-less token.
  """
  use EzagentCore.DataCase, async: false

  alias Ezagent.Workspace
  alias Ezagent.ActionSet.KindBase
  alias Ezagent.Socialware.{AnonAdmission, ExternalFeed}
  alias EzagentPluginHello.{App, KanbanDelegation, Spec, TurnDriver}

  setup do
    :ok = EzagentPluginHello.TestCatalog.import!()
    # `ensure_app` creates the orchestrator via the RF-5a role-create path, which
    # resolves `hello.orchestrator` through the "role-as-data" RecipeRegistry. Boot
    # seeds it, but that write is outside this DataCase sandbox transaction (and the
    # ETS cache can be flushed by another test) — so seed the roles here (idempotent).
    {:ok, _} = Application.ensure_all_started(:ezagent_domain_agent)
    # The `hello.llm` role materializes as a "curl" flavor agent — the flavor is
    # boot-registered by the curl_agent plugin's `agent_flavors/0`, so it must be
    # started here (it is not a transitive dep of anything else this test starts).
    {:ok, _} = Application.ensure_all_started(:ezagent_plugin_curl_agent)
    {:ok, _} = Application.ensure_all_started(:ezagent_plugin_kanban)

    Enum.each(EzagentPluginHello.Application.roles(), fn recipe ->
      {:ok, _} = Ezagent.Agent.RecipeRegistry.seed_role_if_absent(recipe)
    end)

    {:ok, _} =
      Ezagent.Agent.RecipeRegistry.seed_role_if_absent(
        EzagentPluginKanban.Application.kanban_manager_recipe()
      )

    ws = "hello-e2e-#{System.unique_integer([:positive])}"
    {:ok, _ws_pid} = Workspace.create(ws, %{})

    {:ok, session_uri, orchestrator_uri} = App.ensure_app(ws, "main")
    anon = mint_and_join_anon(session_uri)

    %{session: session_uri, orchestrator: orchestrator_uri, caller: anon}
  end

  # The production anonymous ingress (ExternalFeedController.mint_fresh): mint a
  # read-only anon-User for the public_view session, bring its Kind live, join it,
  # and mount the read-only participation tier — so the LIVE membership read
  # authorizes it.
  defp mint_and_join_anon(session_uri) do
    {:ok, %{anon_uri: anon_uri}} = AnonAdmission.admit_anonymous_participant(session_uri)
    anon_uri
  end

  test "an anonymous viewer sees the catalog page the builder lands via Surface", ctx do
    spec = %{
      "type" => "Stack",
      "props" => %{"direction" => "vertical", "title" => "Hello E2E"},
      "children" => [
        %{
          "type" => "Heading",
          "props" => %{"text" => "Generated by the hello builder", "level" => 1},
          "children" => []
        },
        %{
          "type" => "Text",
          "props" => %{"text" => "An anonymous visitor can read this page."},
          "children" => []
        }
      ]
    }

    # The spec is catalog-constrained (the safety property the renderer relies on).
    assert {:ok, ^spec} = Spec.validate(spec)

    # Before any turn: the external surface has no approved page.
    assert {:ok, before} = ExternalFeed.snapshot(ctx.session, ctx.caller)
    assert before.page == nil

    # Drive one turn to land the page (the only way a page is born).
    assert {:ok, _turn_id} = TurnDriver.drive(ctx.session, spec, "Generated your page.")

    snapshot = wait_for_page(ctx.session, ctx.caller)

    # The anon visitor sees exactly the approved spec + the external-visible summary.
    assert snapshot.page == spec
    assert Enum.any?(snapshot.messages, &(text_of(&1) == "Generated your page."))
  end

  test "the shipped seed is a recording-ready Hello product entry" do
    body_path = Path.join(:code.priv_dir(:ezagent_plugin_hello), "seed_page/body.json")
    body = body_path |> File.read!() |> Jason.decode!()
    text = seed_text(body)
    classes = seed_classes(body)

    assert {:ok, ^body} = Spec.validate(body)
    assert "hello · 生成层 · generation" in text
    assert "一句话生成可用界面" in text
    assert "第二次描述继续修改" in text
    assert "确认后派给 Kanban" in text
    assert Enum.any?(text, &String.starts_with?(&1, "派个任务"))
    assert "松耦合，非最终挂载" in text
    assert "hello-product-entry" in classes
    assert "hello-task-cta" in classes
    assert "hello-coupling-boundary" in classes
  end

  test "ensure_app joins the orchestrator front desk without minting a within-session cap", ctx do
    orchestrator = ctx.orchestrator

    assert %{^orchestrator => %{role_name: "front-desk"}} =
             Ezagent.Orchestrator.Tools.read_members(ctx.session)

    {:ok, %{caps: caps}} = Ezagent.Kind.read(ctx.orchestrator, :identity, spawn: :never)

    refute Enum.any?(caps, fn
             %Ezagent.Capability{kind: :session, instance: {:within_session, %URI{} = s}} ->
               URI.to_string(s) == URI.to_string(ctx.session)

             _ ->
               false
           end)

    assert {:error, :unauthorized} =
             Ezagent.Orchestrator.Tools.preflight_within_session_cap(
               orchestrator,
               caps,
               ctx.session,
               :any
             )
  end

  test "ensure_app spawns the session through the socialware install set", ctx do
    {:ok, slice} = Ezagent.Kind.read(ctx.session, :kind_base, spawn: :never)
    behaviors = KindBase.behaviors_in_slice(slice)

    assert Ezagent.ActionSet.Session in behaviors
    assert Ezagent.ActionSet.Turn in behaviors
    assert Ezagent.ActionSet.Surface in behaviors
    assert Ezagent.ActionSet.Publisher.SessionImpl in behaviors
  end

  test "a second validated prompt result changes the live anonymous page", ctx do
    first = Spec.seed()

    second =
      put_in(first, ["children", Access.at(0), "props", "text"], "A warmer second prompt")

    assert {:ok, ^first} = Spec.validate(first)
    assert {:ok, ^second} = Spec.validate(second)
    assert {:ok, _} = TurnDriver.drive(ctx.session, first, "First version")
    assert %{page: ^first} = wait_for_page_value(ctx.session, ctx.caller, first)
    assert {:ok, _} = TurnDriver.drive(ctx.session, second, "Second version")

    snapshot = wait_for_page_value(ctx.session, ctx.caller, second)
    assert snapshot.page == second
    refute snapshot.page == first
  end

  test "hello delegation creates a real Kanban node without mutating the Surface", ctx do
    spec = Spec.seed()
    assert {:ok, _} = TurnDriver.drive(ctx.session, spec, "Page ready")
    assert %{page: ^spec} = wait_for_page_value(ctx.session, ctx.caller, spec)
    assert {:ok, surface_before} = Ezagent.Kind.read(ctx.session, :surface, spawn: :never)

    assert {:ok, result} =
             KanbanDelegation.delegate(
               ctx.session,
               "Ship the hello landing page",
               Ezagent.Entity.User.admin_uri()
             )

    assert {:ok, surface_after} = Ezagent.Kind.read(ctx.session, :surface, spawn: :never)
    assert surface_after == surface_before

    target = Ezagent.URI.with_action(result.kanban_uri, :kanban, :get_tree)
    admin = Ezagent.Entity.User.admin_uri()
    cap = Ezagent.Test.CapHelper.signed_action_cap!(target, admin)

    assert {:ok, %{tree: tree}} =
             Ezagent.Invocation.dispatch(%Ezagent.Invocation{
               origin: :trusted_internal,
               target: target,
               mode: :call,
               args: %{},
               ctx: %{
                 caller: admin,
                 authenticated_principal: admin,
                 caps: MapSet.new([cap]),
                 reply: {:caller_inbox, self()}
               }
             })

    assert tree.nodes[result.node_id].title == "Ship the hello landing page"
    assert [artifact] = tree.nodes[result.node_id].artifacts
    assert artifact.kind == "hello_source"
  end

  test "INV-CC ②: a session with the curl llm member is created even with NO credential source" do
    # A fresh workspace in this test env has no DeepSeek credential source
    # provisioned — this is exactly the deployment shape `credential_optional`
    # (Task 1) exists to keep working.
    ws = "hello-e2e-llm-#{System.unique_integer([:positive])}"
    {:ok, _ws_pid} = Workspace.create(ws, %{})

    assert {:ok, session_uri, _orch} = App.ensure_app(ws, "llm-keyless")
    # llm curl member materialized (keyless — did not crash session-create).
    assert {:ok, %URI{}} = EzagentPluginHello.Members.role_uri(session_uri, "llm")
  end

  # --- helpers ---------------------------------------------------------------

  defp wait_for_page(session, caller, attempts \\ 150)

  defp wait_for_page(_session, _caller, 0),
    do: flunk("external snapshot never exposed an approved page")

  defp wait_for_page(session, caller, attempts) do
    case ExternalFeed.snapshot(session, caller) do
      # Await a SETTLED (non-straddled) snapshot: `snapshot/2` reads messages,
      # surface and committed-version non-atomically, so at the settling poll the
      # page can be present while the message list is still []. Production replays
      # the message on {:external_delivery}; here we simply wait one more poll for
      # the message to appear, matching the fresh snapshot production ends up with.
      {:ok, %{page: page, messages: messages} = snapshot}
      when not is_nil(page) and messages != [] ->
        snapshot

      _ ->
        Process.sleep(20)
        wait_for_page(session, caller, attempts - 1)
    end
  end

  defp wait_for_page_value(session, caller, expected, attempts \\ 150)

  defp wait_for_page_value(_session, _caller, _expected, 0),
    do: flunk("external snapshot never exposed the expected approved page")

  defp wait_for_page_value(session, caller, expected, attempts) do
    case ExternalFeed.snapshot(session, caller) do
      {:ok, %{page: ^expected} = snapshot} ->
        snapshot

      _ ->
        Process.sleep(20)
        wait_for_page_value(session, caller, expected, attempts - 1)
    end
  end

  defp text_of(message) do
    Map.get(message.body, "text") || Map.get(message.body, :text)
  end

  defp seed_text(%{"children" => children, "props" => props}) do
    own = [props["text"], props["label"]] |> Enum.reject(&is_nil/1)
    own ++ Enum.flat_map(children, &seed_text/1)
  end

  defp seed_text(_), do: []

  defp seed_classes(%{"children" => children, "props" => props}) do
    own = if is_binary(props["className"]), do: String.split(props["className"]), else: []
    own ++ Enum.flat_map(children, &seed_classes/1)
  end

  defp seed_classes(_), do: []
end
